trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'ProMag.Server/ProMag.Server.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: "dotnet build $(buildConfiguration)"
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: 'ProMag.Server/*UnitTest/*.csproj'
    testRunTitle: 'xUnit Test Run'

