trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solutionPath: 'ProMag.Server/ProMag.Server.sln'
  unitTestPath: 'ProMag.Server/*UnitTest/*.csproj'
  apiProjectPath: 'ProMag.Server/*Api/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
- script: dotnet build $(solutionPath) --configuration $(buildConfiguration)
  displayName: "dotnet build $(buildConfiguration)"
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: $(unitTestPath)
    testRunTitle: 'xUnit Test Run'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: $(apiProjectPath)
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
